services:
  postgres:
    image: postgres:16
    container_name: org_structure_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: org_structure
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d org_structure"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    container_name: org_structure_migrate
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      /app/goose -dir /app/migrations postgres
      postgres://postgres:postgres@postgres:5432/org_structure?sslmode=disable
      up
    restart: "no"

  app:
    build: .
    container_name: org_structure_app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      HTTP_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: org_structure
    ports:
      - "8080:8080"

volumes:
  postgres_data: